language: elixir
elixir:
  - 1.2.2
deploy:
  provider: heroku
  api_key:
    secure: YgNo2JT2cITooTfjmGP9Ahq84hvmuIal2vPb98DZXInaAynMDkXIjT7/3sLtHSSiYx6nWVLjKFgoToCcweFZ7fw93lrZcx1n3GYR4Lzvdj+tkMtilIeiUmkxdQSk/cDm8/Y3TZU1KiiJkwIomrsPCJjku38EarbUz5wZtyaxK4pqaupW+YaySbXlubbjav7BRP7b0sehDjd55ZSOpj3RVFtTjx5ookdwZ2+46i0UFBEXidYOsNhDw+CQXZmMej6sSN+alWBLWK/RJNFijX4D0CIN0n5tntTV9xo/jM0LBeDCkztv0gHm+C1G0dH8uQaOH4eX2vOnkQ/7MxFSOoJukMF6CBGu03/JUtMC+TFGCs4jTe8RB21+uaLCbpQt9Ah0AKM1uQJt2amPTxdjtD5PRZfLaDlmxIkr/1bjgIfwV8+jQtUHskI0nRTDkuhetPmoP1je3cQjkb7PTMm6mH6cHeAge9JRBGkMtdFyc5TG4ASy+oJIQ2qKu+ZgkYbV+F4IJGbbFDAFtHX6yZokhm2ORkYW41zu3CKJRV/D/qKroY1oe9Phm2QeoX9jg74Cwetyhm1LMmgnpOVT3j0HFQCaPHRPQy8OqgwySICNcunBD3gyYCBHQNI40UTrzxNrqEKEqAG2/0WJm2Cusi9ig6gudtk/NUEBVOrH+YZKceUqwfE=
notifications:
  email: false
